font_family      family='SFMono Nerd Font' postscript_name=SFMonoNF-Regular


macos_option_as_alt left
map alt+left  send_text all \eb
map alt+right send_text all \ef

macos_quit_when_last_window_closed yes
macos_titlebar_color     background
# map cmd+c copy_to_clipboard
# map cmd+v paste_from_clipboard

# Cmd+T New Tab, Cmd+W Close Tab
map cmd+t new_tab
map cmd+w close_tab

# Cmd+Number Switch Tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
